from __future__ import annotations

import sqlite3
from collections import defaultdict, deque
from typing import Any, Iterable, Sequence

from .model import SCHEMA_VERSION, canonical_hash, canonical_json, new_id
from .store import TestamurStore as _BaseTestamurStore, utc_now

# These tokens are part of historical content-addressed envelopes. Renaming them
# would change durable hashes, so they remain compatibility serialization inputs
# rather than current product/runtime identity.
CONTENT_ADDRESS_VERSION = "witness-cas-v0.1"
SNAPSHOT_VERSION = "witness-snapshot-v0.1"
STATE_REVISION_VERSION = "witness-state-revision-v0.1"


class LegacyRevisionStore(_BaseTestamurStore):
    """Internal compatibility implementation for historical revision/CAS data.

    Historical physical tables and serialization tokens remain stable so old
    databases reopen. Public callers use ``testamur.revision_store``; new base
    graph identities are generated by the Testamur-owned parent store.
    """

    def _init_schema(self) -> None:
        super()._init_schema()
        schema = """
        CREATE TABLE IF NOT EXISTS witness_revision_parents(child_revision_id TEXT NOT NULL REFERENCES witness_revisions(id),parent_revision_id TEXT NOT NULL REFERENCES witness_revisions(id),position INTEGER NOT NULL,PRIMARY KEY(child_revision_id,parent_revision_id),UNIQUE(child_revision_id,position));
        CREATE TABLE IF NOT EXISTS witness_content_objects(address TEXT PRIMARY KEY,object_type TEXT NOT NULL,content_json TEXT NOT NULL,byte_length INTEGER NOT NULL,created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS witness_state_revisions(address TEXT PRIMARY KEY REFERENCES witness_content_objects(address),project_id TEXT NOT NULL REFERENCES witness_projects(id),snapshot_address TEXT NOT NULL REFERENCES witness_content_objects(address),created_at TEXT NOT NULL,actor_ref TEXT NOT NULL DEFAULT '',message TEXT NOT NULL DEFAULT '');
        CREATE TABLE IF NOT EXISTS witness_state_revision_parents(child_address TEXT NOT NULL REFERENCES witness_state_revisions(address),parent_address TEXT NOT NULL REFERENCES witness_state_revisions(address),position INTEGER NOT NULL,PRIMARY KEY(child_address,parent_address),UNIQUE(child_address,position));
        CREATE TABLE IF NOT EXISTS witness_state_heads(project_id TEXT PRIMARY KEY REFERENCES witness_projects(id),revision_address TEXT NOT NULL REFERENCES witness_state_revisions(address),updated_at TEXT NOT NULL);
        CREATE TRIGGER IF NOT EXISTS witness_revision_parents_no_update BEFORE UPDATE ON witness_revision_parents BEGIN SELECT RAISE(ABORT,'Revision parent links are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_revision_parents_no_delete BEFORE DELETE ON witness_revision_parents BEGIN SELECT RAISE(ABORT,'Revision parent links are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_content_objects_no_update BEFORE UPDATE ON witness_content_objects BEGIN SELECT RAISE(ABORT,'Content-addressed objects are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_content_objects_no_delete BEFORE DELETE ON witness_content_objects BEGIN SELECT RAISE(ABORT,'Content-addressed objects are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_state_revisions_no_update BEFORE UPDATE ON witness_state_revisions BEGIN SELECT RAISE(ABORT,'State revisions are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_state_revisions_no_delete BEFORE DELETE ON witness_state_revisions BEGIN SELECT RAISE(ABORT,'State revisions are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_state_revision_parents_no_update BEFORE UPDATE ON witness_state_revision_parents BEGIN SELECT RAISE(ABORT,'State revision parent links are immutable'); END;
        CREATE TRIGGER IF NOT EXISTS witness_state_revision_parents_no_delete BEFORE DELETE ON witness_state_revision_parents BEGIN SELECT RAISE(ABORT,'State revision parent links are immutable'); END;
        """
        with self.connect() as conn: conn.executescript(schema)

    def _put_content(self, conn: sqlite3.Connection, object_type: str, payload: dict[str, Any]) -> str:
        envelope={"schema_version":SCHEMA_VERSION,"content_address_version":CONTENT_ADDRESS_VERSION,"object_type":object_type,"payload":payload}; address=f"sha256:{canonical_hash(envelope)}"; body=canonical_json(envelope)
        conn.execute("INSERT OR IGNORE INTO witness_content_objects(address,object_type,content_json,byte_length,created_at) VALUES(?,?,?,?,?)",(address,object_type,body,len(body.encode("utf-8")),utc_now())); return address

    def _get_content_conn(self,conn:sqlite3.Connection,address:str,*,expected_type:str|None=None)->dict[str,Any]:
        row=conn.execute("SELECT * FROM witness_content_objects WHERE address=?",(address,)).fetchone()
        if not row: raise KeyError(address)
        envelope=self._load(row["content_json"])
        if f"sha256:{canonical_hash(envelope)}" != address: raise ValueError(f"content address mismatch: {address}")
        if expected_type is not None and envelope.get("object_type") != expected_type: raise ValueError(f"content object {address} is not {expected_type}")
        return envelope["payload"]

    def get_content(self,address:str)->dict[str,Any]:
        with self.connect() as conn: return self._get_content_conn(conn,address)

    def _record_revision_parents(self,conn:sqlite3.Connection,child_revision_id:str,parent_revision_ids:Sequence[str])->None:
        for position,parent_id in enumerate(parent_revision_ids): conn.execute("INSERT INTO witness_revision_parents(child_revision_id,parent_revision_id,position) VALUES(?,?,?)",(child_revision_id,parent_id,position))

    def create_object(self,project:str,kind:str,payload:dict[str,Any],*,actor_ref:str="")->dict[str,Any]:
        return super().create_object(project,kind,payload,actor_ref=actor_ref)

    def revision_parents(self,revision_id:str)->list[str]:
        with self.connect() as conn: rows=conn.execute("SELECT parent_revision_id FROM witness_revision_parents WHERE child_revision_id=? ORDER BY position",(revision_id,)).fetchall()
        return [str(row["parent_revision_id"]) for row in rows]

    def revise_object(self,object_id:str,payload:dict[str,Any],*,actor_ref:str="",parent_revision_ids:Iterable[str]|None=None)->dict[str,Any]:
        if not isinstance(payload,dict) or not payload: raise ValueError("Testamur revision payload must be a non-empty object")
        now=utc_now(); revision_id=new_id("trv")
        with self.connect() as conn:
            project_id=self._object_project(conn,object_id); previous=self._latest_revision_row(conn,object_id)
            parents=[str(previous["id"])] if parent_revision_ids is None else list(dict.fromkeys(str(item) for item in parent_revision_ids))
            if not parents: raise ValueError("a non-root object revision must have at least one parent")
            for parent_id in parents:
                parent=conn.execute("SELECT object_id FROM witness_revisions WHERE id=?",(parent_id,)).fetchone()
                if not parent: raise KeyError(parent_id)
                if str(parent["object_id"])!=object_id: raise ValueError("object revision parents must belong to the same object")
            revision_no=int(previous["revision_no"])+1
            conn.execute("INSERT INTO witness_revisions(id,object_id,revision_no,payload_json,content_hash,actor_ref,created_at) VALUES(?,?,?,?,?,?,?)",(revision_id,object_id,revision_no,self._json(payload),canonical_hash(payload),actor_ref,now)); self._record_revision_parents(conn,revision_id,parents); self._event(conn,project_id,"object_revised",object_id,{"revision_id":revision_id,"revision_no":revision_no,"parent_revision_ids":parents,"previous_revision_id":previous["id"]})
        return self.get_object(object_id)

    def _snapshot_manifest(self,conn:sqlite3.Connection,project_id:str)->dict[str,Any]:
        project=dict(conn.execute("SELECT * FROM witness_projects WHERE id=?",(project_id,)).fetchone()); project_ref=self._put_content(conn,"project",project); object_refs={}; revision_refs={}; edge_refs={}; run_refs={}; event_refs={}
        for row in conn.execute("SELECT * FROM witness_objects WHERE project_id=? ORDER BY created_at,id",(project_id,)).fetchall(): object_refs[str(row["id"])]=self._put_content(conn,"object",dict(row))
        for row in conn.execute("SELECT r.* FROM witness_revisions r JOIN witness_objects o ON o.id=r.object_id WHERE o.project_id=? ORDER BY r.object_id,r.revision_no",(project_id,)).fetchall():
            record=dict(row); record["payload"]=self._load(record.pop("payload_json")); record["parent_revision_ids"]=self.revision_parents(str(row["id"])); revision_refs[str(row["id"])]=self._put_content(conn,"object_revision",record)
        for row in conn.execute("SELECT * FROM witness_edges WHERE project_id=? ORDER BY created_at,id",(project_id,)).fetchall(): record=dict(row); record["payload"]=self._load(record.pop("payload_json")); edge_refs[str(row["id"])]=self._put_content(conn,"edge",record)
        for row in conn.execute("SELECT * FROM witness_verification_runs WHERE project_id=? ORDER BY created_at,id",(project_id,)).fetchall():
            record=dict(row)
            for key in ("input_revisions_json","environment_json","result_json","artifact_ids_json"): record[key[:-5]]=self._load(record.pop(key))
            run_refs[str(row["id"])]=self._put_content(conn,"verification_run",record)
        for row in conn.execute("SELECT * FROM witness_events WHERE project_id=? ORDER BY seq",(project_id,)).fetchall(): record=dict(row); record["payload"]=self._load(record.pop("payload_json")); event_refs[str(row["seq"])]=self._put_content(conn,"event",record)
        return {"snapshot_version":SNAPSHOT_VERSION,"schema_version":SCHEMA_VERSION,"project_id":project_id,"project":project_ref,"objects":object_refs,"revisions":revision_refs,"edges":edge_refs,"verification_runs":run_refs,"events":event_refs}

    def commit_project_revision(self,project:str,*,parent_addresses:Iterable[str]|None=None,actor_ref:str="",message:str="")->dict[str,Any]:
        project_id=self._project_id(project); now=utc_now()
        with self.connect() as conn:
            manifest=self._snapshot_manifest(conn,project_id); snapshot_address=self._put_content(conn,"snapshot",manifest)
            if parent_addresses is None:
                head=conn.execute("SELECT revision_address FROM witness_state_heads WHERE project_id=?",(project_id,)).fetchone(); parents=[] if head is None else [str(head["revision_address"])]
            else: parents=list(dict.fromkeys(str(item) for item in parent_addresses))
            for parent in parents:
                row=conn.execute("SELECT project_id FROM witness_state_revisions WHERE address=?",(parent,)).fetchone()
                if not row: raise KeyError(parent)
                if str(row["project_id"])!=project_id: raise ValueError("state revision parents cannot cross projects")
            envelope={"state_revision_version":STATE_REVISION_VERSION,"schema_version":SCHEMA_VERSION,"project_id":project_id,"snapshot_address":snapshot_address,"parent_addresses":parents,"actor_ref":actor_ref,"message":message,"created_at":now}; address=self._put_content(conn,"state_revision",envelope)
            conn.execute("INSERT OR IGNORE INTO witness_state_revisions(address,project_id,snapshot_address,created_at,actor_ref,message) VALUES(?,?,?,?,?,?)",(address,project_id,snapshot_address,now,actor_ref,message))
            for position,parent in enumerate(parents): conn.execute("INSERT OR IGNORE INTO witness_state_revision_parents(child_address,parent_address,position) VALUES(?,?,?)",(address,parent,position))
            conn.execute("INSERT INTO witness_state_heads(project_id,revision_address,updated_at) VALUES(?,?,?) ON CONFLICT(project_id) DO UPDATE SET revision_address=excluded.revision_address,updated_at=excluded.updated_at",(project_id,address,now)); self._event(conn,project_id,"state_revision_committed",address,{"snapshot_address":snapshot_address,"parent_addresses":parents})
        return self.get_state_revision(address)

    def get_state_revision(self,address:str)->dict[str,Any]:
        with self.connect() as conn:
            row=conn.execute("SELECT * FROM witness_state_revisions WHERE address=?",(address,)).fetchone()
            if not row: raise KeyError(address)
            parents=[str(item["parent_address"]) for item in conn.execute("SELECT parent_address FROM witness_state_revision_parents WHERE child_address=? ORDER BY position",(address,)).fetchall()]
        return {"address":address,"project_id":row["project_id"],"snapshot_address":row["snapshot_address"],"parent_addresses":parents,"actor_ref":row["actor_ref"],"message":row["message"],"created_at":row["created_at"]}

    def _state_revision_conn(self,conn:sqlite3.Connection,address:str)->sqlite3.Row:
        row=conn.execute("SELECT * FROM witness_state_revisions WHERE address=?",(address,)).fetchone()
        if not row: raise KeyError(address)
        return row

    def reconstruct_revision(self,revision_address:str)->dict[str,Any]:
        with self.connect() as conn:
            state=self._state_revision_conn(conn,revision_address); manifest=self._get_content_conn(conn,state["snapshot_address"],expected_type="snapshot")
            def load_map(key:str,kind:str)->list[dict[str,Any]]: return [self._get_content_conn(conn,ref,expected_type=kind) for _,ref in sorted((manifest.get(key) or {}).items())]
            project=self._get_content_conn(conn,manifest["project"],expected_type="project"); objects=load_map("objects","object"); revisions=load_map("revisions","object_revision"); edges=load_map("edges","edge"); runs=load_map("verification_runs","verification_run"); events=load_map("events","event")
        return {"revision":self.get_state_revision(revision_address),"manifest":manifest,"project":project,"objects":objects,"revisions":revisions,"edges":edges,"verification_runs":runs,"events":events}

    def verify_revision_integrity(self,revision_address:str)->dict[str,Any]:
        errors=[]; checked=0
        try:
            reconstructed=self.reconstruct_revision(revision_address); checked=1+len(reconstructed["objects"])+len(reconstructed["revisions"])+len(reconstructed["edges"])+len(reconstructed["verification_runs"])+len(reconstructed["events"])
        except (KeyError,ValueError,sqlite3.DatabaseError) as exc: errors.append(str(exc))
        return {"ok":not errors,"revision_address":revision_address,"checked_objects":checked,"errors":errors}

    def revision_ancestors(self,revision_address:str)->list[str]:
        with self.connect() as conn:
            seen=set(); queue=deque([revision_address]); result=[]
            while queue:
                child=queue.popleft()
                for row in conn.execute("SELECT parent_address FROM witness_state_revision_parents WHERE child_address=? ORDER BY position",(child,)).fetchall():
                    parent=str(row["parent_address"])
                    if parent not in seen: seen.add(parent); result.append(parent); queue.append(parent)
        return result

    def state_head(self,project:str)->dict[str,Any]|None:
        project_id=self._project_id(project)
        with self.connect() as conn: row=conn.execute("SELECT revision_address FROM witness_state_heads WHERE project_id=?",(project_id,)).fetchone()
        return None if row is None else self.get_state_revision(str(row["revision_address"]))


__all__=["CONTENT_ADDRESS_VERSION","SNAPSHOT_VERSION","STATE_REVISION_VERSION","LegacyRevisionStore"]
